### PR TITLE
169 porter operator manager unable to create agent actions if agent config is overwritten

### LINKED ISSUE #169: Porter operator manager unable to create agent actions  if agent config is overwritten
## Describe the bug
Updating values in the agentconfig and reapplying makes the operator unable to process agent actions. The controller sees a new agent config come through and creates a job to handle that. It tries to associate the new PVC to the hashed PVC for the plugins but is unable to do that and so the agentconfig never gets into the "ready: true" state.

## To Reproduce
1. Apply an agent config and use it to create an installation
2. Update a value in the agent config (ex: VolumeSize)
3. Observe that agent config does not become "ready"
4. Attempt to create a new installation, it is unable to apply agent action because the agent config is not ready

## Expected behavior
Updates to an existing agent config should result in it becoming ready to use

## Operator execution and Output
Agent Config patch
```
porter-operator-controller-manager-744fdcdb49-qhs96:manager 2023-03-01T20:41:33Z    DEBUG    controllers.AgentConfig    Applied patch    {"agent config": "default", "namespace": "vulcan", "resourceVersion": "55547293", "generation": 3, "observe
dGeneration": 3, "status": false, "agentaction": "default-ptwgt", "data": "{\"metadata\":{\"managedFields\":[{\"apiVersion\":\"getporter.org/v1\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:metadata\":{\"f:finalizers\":{\".\":{},\"v:\\\"getpo
rter.org/finalizer\\\"\":{}}}},\"manager\":\"manager\",\"operation\":\"Update\",\"time\":\"2023-03-01T20:29:50Z\"},{\"apiVersion\":\"getporter.org/v1\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:metadata\":{\"f:annotations\":{\".\":{},\"f:ku
bectl.kubernetes.io/last-applied-configuration\":{}},\"f:labels\":{\".\":{},\"f:cedi.octo.f5net.com/app\":{},\"f:cedi.octo.f5net.com/gitSha\":{},\"f:cedi.octo.f5net.com/version\":{},\"f:getporter.org/generator\":{},\"f:porter.sh/generator\":{}}
},\"f:spec\":{\".\":{},\"f:pluginConfigFile\":{\".\":{},\"f:plugins\":{\".\":{},\"f:azure\":{\".\":{},\"f:version\":{}},\"f:kubernetes\":{\".\":{},\"f:version\":{}}},\"f:schemaVersion\":{}},\"f:porterRepository\":{},\"f:porterVersion\":{},\"f:p
ullPolicy\":{},\"f:serviceAccount\":{},\"f:storageClassName\":{},\"f:volumeSize\":{}}},\"manager\":\"kubectl-client-side-apply\",\"operation\":\"Update\",\"time\":\"2023-03-01T20:41:17Z\"},{\"apiVersion\":\"getporter.org/v1\",\"fieldsType\":\"F
ieldsV1\",\"fieldsV1\":{\"f:status\":{\".\":{},\"f:action\":{\".\":{},\"f:name\":{}},\"f:conditions\":{},\"f:observedGeneration\":{},\"f:phase\":{},\"f:ready\":{}}},\"manager\":\"manager\",\"operation\":\"Update\",\"subresource\":\"status\",\"t
ime\":\"2023-03-01T20:41:33Z\"}],\"resourceVersion\":\"55547389\"},\"status\":{\"phase\":\"Pending\"}}"}                                                                                                                                            
porter-operator-controller-manager-744fdcdb49-qhs96:manager 2023-03-01T20:41:33Z    DEBUG    controllers.AgentConfig    Temporary plugin persistent volume claims found    {"agent config": "default", "namespace": "vulcan", "resourceVersion": "55
547293", "generation": 3, "observedGeneration": 3, "status": false, "agentaction": "default-ptwgt", "persistentvolumeclaim": "default-68h65", "namespace": "vulcan", "status": "Bound"}                                                             
porter-operator-controller-manager-744fdcdb49-qhs96:manager 2023-03-01T20:41:33Z    DEBUG    controllers.AgentConfig    Plugin persistent volume claims found    {"agent config": "default", "namespace": "vulcan", "resourceVersion": "55547293", "
generation": 3, "observedGeneration": 3, "status": false, "agentaction": "default-ptwgt", "persistentvolumeclaim": "porter-b893638aaf9742a0d5678ca098d12e78", "namespace": "vulcan", "status": "Bound"}                                             
porter-operator-controller-manager-744fdcdb49-qhs96:manager 2023-03-01T20:41:33Z    DEBUG    controllers.AgentConfig    Existing volume and agent Status    {"agent config": "default", "namespace": "vulcan", "resourceVersion": "55547293", "gener
ation": 3, "observedGeneration": 3, "status": false, "agentaction": "default-ptwgt", "volume status": false, "agent status": false}                                                                                                                 
porter-operator-controller-manager-744fdcdb49-qhs96:manager 2023-03-01T20:41:33Z    DEBUG    controllers.AgentConfig    Plugins is not ready yet.    {"agent config": "default", "namespace": "vulcan", "resourceVersion": "55547293", "generation":
 3, "observedGeneration": 3, "status": false, "agentaction": "default-ptwgt", "action status": {"observedGeneration":1,"job":{"name":"default-ptwgt-qf6zl"},"phase":"Pending","conditions":[{"type":"Scheduled","status":"True","observedGeneration"
:1,"lastTransitionTime":"2023-03-01T20:41:17Z","reason":"JobCreated","message":""},{"type":"Started","status":"True","observedGeneration":1,"lastTransitionTime":"2023-03-01T20:41:17Z","reason":"JobStarted","message":""}]}}                      
porter-operator-controller-manager-744fdcdb49-qhs96:manager 2023-03-01T20:41:33Z    DEBUG    controllers.AgentAction    Applied patch    {"agentaction": "default-ptwgt", "namespace": "vulcan", "resourceVersion": "55547385", "generation": 1, "ob
servedGeneration": 1, "data": "{\"metadata\":{\"resourceVersion\":\"55547390\"},\"status\":{\"conditions\":[{\"lastTransitionTime\":\"2023-03-01T20:41:17Z\",\"message\":\"\",\"observedGeneration\":1,\"reason\":\"JobCreated\",\"status\":\"True\"
,\"type\":\"Scheduled\"},{\"lastTransitionTime\":\"2023-03-01T20:41:17Z\",\"message\":\"\",\"observedGeneration\":1,\"reason\":\"JobStarted\",\"status\":\"True\",\"type\":\"Started\"},{\"lastTransitionTime\":\"2023-03-01T20:41:33Z\",\"message\"
:\"\",\"observedGeneration\":1,\"reason\":\"JobCompleted\",\"status\":\"True\",\"type\":\"Completed\"}],\"phase\":\"Succeeded\"}}"}                                                                                                                 
porter-operator-controller-manager-744fdcdb49-qhs96:manager 2023-03-01T20:41:33Z    DEBUG    controllers.AgentAction    Reconciliation complete: A porter agent has already been dispatched.    {"agentaction": "default-ptwgt", "namespace": "vulca
n", "resourceVersion": "55547385", "generation": 1, "observedGeneration": 1}                                                                                                                                                                        
porter-operator-controller-manager-744fdcdb49-qhs96:manager 2023-03-01T20:41:33Z    INFO    controllers.AgentConfig    Reconciling agent config    {"agent config": "default", "namespace": "vulcan", "resourceVersion": "55547389", "generation": 3
, "observedGeneration": 3, "status": false}                                                                                                                                                                                                         
porter-operator-controller-manager-744fdcdb49-qhs96:manager 2023-03-01T20:41:33Z    DEBUG    controllers.AgentConfig    Found existing agent action    {"agent config": "default", "namespace": "vulcan", "resourceVersion": "55547389", "generation
": 3, "observedGeneration": 3, "status": false, "agentaction": "default-ptwgt"}                                                                                                                                                                     
porter-operator-controller-manager-744fdcdb49-qhs96:manager 2023-03-01T20:41:33Z    INFO    controllers.AgentConfig    Syncing AgentAction status with AgentConfig    {"agent config": "default", "namespace": "vulcan", "resourceVersion": "5554738
9", "generation": 3, "observedGeneration": 3, "status": false, "agentaction": "default-ptwgt"}                                                                                                                                                      
porter-operator-controller-manager-744fdcdb49-qhs96:manager 2023-03-01T20:41:33Z    INFO    controllers.AgentConfig    Copied status from agent action    {"agent config": "default", "namespace": "vulcan", "resourceVersion": "55547389", "generat
ion": 3, "observedGeneration": 3, "status": false, "agentaction": "default-ptwgt", "action": "default-ptwgt", "phase": "Succeeded", "conditions": ["Scheduled", "Started", "Completed"]}                                                            
porter-operator-controller-manager-744fdcdb49-qhs96:manager 2023-03-01T20:41:33Z    INFO    controllers.AgentConfig    Patching agent config status    {"agent config": "default", "namespace": "vulcan", "resourceVersion": "55547389", "generation
": 3, "observedGeneration": 3, "status": false, "agentaction": "default-ptwgt"}                                                                                                                                                                     
porter-operator-controller-manager-744fdcdb49-qhs96:manager 2023-03-01T20:41:33Z    DEBUG    controllers.AgentConfig    Applied patch    {"agent config": "default", "namespace": "vulcan", "resourceVersion": "55547389", "generation": 3, "observe
dGeneration": 3, "status": false, "agentaction": "default-ptwgt", "data": "{\"metadata\":{\"resourceVersion\":\"55547391\"},\"status\":{\"conditions\":[{\"lastTransitionTime\":\"2023-03-01T20:41:17Z\",\"message\":\"\",\"observedGeneration\":1,\
"reason\":\"JobCreated\",\"status\":\"True\",\"type\":\"Scheduled\"},{\"lastTransitionTime\":\"2023-03-01T20:41:17Z\",\"message\":\"\",\"observedGeneration\":1,\"reason\":\"JobStarted\",\"status\":\"True\",\"type\":\"Started\"},{\"lastTransitio
nTime\":\"2023-03-01T20:41:33Z\",\"message\":\"\",\"observedGeneration\":1,\"reason\":\"JobCompleted\",\"status\":\"True\",\"type\":\"Completed\"}],\"phase\":\"Succeeded\"}}"}                                                                     
porter-operator-controller-manager-744fdcdb49-qhs96:manager 2023-03-01T20:41:33Z    DEBUG    controllers.AgentConfig    Temporary plugin persistent volume claims found    {"agent config": "default", "namespace": "vulcan", "resourceVersion": "55
547389", "generation": 3, "observedGeneration": 3, "status": false, "agentaction": "default-ptwgt", "persistentvolumeclaim": "default-68h65", "namespace": "vulcan", "status": "Bound"}                                                             
porter-operator-controller-manager-744fdcdb49-qhs96:manager 2023-03-01T20:41:33Z    DEBUG    controllers.AgentConfig    Plugin persistent volume claims found    {"agent config": "default", "namespace": "vulcan", "resourceVersion": "55547389", "
generation": 3, "observedGeneration": 3, "status": false, "agentaction": "default-ptwgt", "persistentvolumeclaim": "porter-b893638aaf9742a0d5678ca098d12e78", "namespace": "vulcan", "status": "Bound"}                                             
porter-operator-controller-manager-744fdcdb49-qhs96:manager 2023-03-01T20:41:33Z    DEBUG    controllers.AgentConfig    Existing volume and agent Status    {"agent config": "default", "namespace": "vulcan", "resourceVersion": "55547389", "gener
ation": 3, "observedGeneration": 3, "status": false, "agentaction": "default-ptwgt", "volume status": false, "agent status": false}                                                                                                                 
porter-operator-controller-manager-744fdcdb49-qhs96:manager 2023-03-01T20:41:33Z    DEBUG    controllers.AgentConfig    Renaming temporary persistent volume claim.    {"agent config": "default", "namespace": "vulcan", "resourceVersion": "555473
89", "generation": 3, "observedGeneration": 3, "status": false, "agentaction": "default-ptwgt", "new persistentvolumeclaim": "porter-b893638aaf9742a0d5678ca098d12e78"}                                                                             
porter-operator-controller-manager-744fdcdb49-qhs96:manager 2023-03-01T20:41:33Z    DEBUG    controllers.AgentConfig    Plugin persistent volume claims found    {"agent config": "default", "namespace": "vulcan", "resourceVersion": "55547389", "
generation": 3, "observedGeneration": 3, "status": false, "agentaction": "default-ptwgt", "persistentvolumeclaim": "porter-b893638aaf9742a0d5678ca098d12e78", "namespace": "vulcan", "status": "Bound"}                                             
porter-operator-controller-manager-744fdcdb49-qhs96:manager 2023-03-01T20:41:33Z    DEBUG    controllers.AgentConfig    Temporary plugin persistent volume claims found    {"agent config": "default", "namespace": "vulcan", "resourceVersion": "55
547389", "generation": 3, "observedGeneration": 3, "status": false, "agentaction": "default-ptwgt", "persistentvolumeclaim": "default-68h65", "namespace": "vulcan", "status": "Bound"} 
```

New installation
```
porter-operator-controller-manager-6fcd6f8d7c-tv74m:manager 2023-03-01T20:34:07Z    INFO    controllers.AgentAction    Reconciling agent action    {"agentaction": "porter-test-me-v0-6-1-jzdz7-2mtb4", "namespace": "vulcan", "resourceVersion": "5
5545010", "generation": 1, "observedGeneration": 1}                                                                                                                                                                                                 
porter-operator-controller-manager-6fcd6f8d7c-tv74m:manager 2023-03-01T20:34:07Z    DEBUG    controllers.AgentAction    No existing job was found    {"agentaction": "porter-test-me-v0-6-1-jzdz7-2mtb4", "namespace": "vulcan", "resourceVersion": 
"55545010", "generation": 1, "observedGeneration": 1}                                                                                                                                                                                               
porter-operator-controller-manager-6fcd6f8d7c-tv74m:manager 2023-03-01T20:34:07Z    INFO    controllers.AgentAction    Cleared status because there is no current job    {"agentaction": "porter-test-me-v0-6-1-jzdz7-2mtb4", "namespace": "vulcan",
 "resourceVersion": "55545010", "generation": 1, "observedGeneration": 1}                                                                                                                                                                           
porter-operator-controller-manager-6fcd6f8d7c-tv74m:manager 2023-03-01T20:34:07Z    INFO    controllers.AgentAction    Porter agent requested    {"agentaction": "porter-test-me-v0-6-1-jzdz7-2mtb4", "namespace": "vulcan", "resourceVersion": "555
45010", "generation": 1, "observedGeneration": 1, "namespace": "vulcan", "action": "porter-test-me-v0-6-1-jzdz7-2mtb4"}                                                                                                                             
porter-operator-controller-manager-6fcd6f8d7c-tv74m:manager 2023-03-01T20:34:07Z    INFO    controllers.AgentAction    Resolving porter agent configuration    {"agentaction": "porter-test-me-v0-6-1-jzdz7-2mtb4", "namespace": "vulcan", "resource
Version": "55545010", "generation": 1, "observedGeneration": 1}                                                                                                                                                                                     
porter-operator-controller-manager-6fcd6f8d7c-tv74m:manager 2023-03-01T20:34:07Z    DEBUG    controllers.AgentAction    Found porter agent configuration    {"agentaction": "porter-test-me-v0-6-1-jzdz7-2mtb4", "namespace": "vulcan", "resourceVer
sion": "55545010", "generation": 1, "observedGeneration": 1, "level": "namespace", "namespace": "vulcan", "name": "default", "plugin": {"schemaVersion":"1.0.0","plugins":{"azure":{"version":"v1.1.2"},"kubernetes":{"version":"v1.0.0"}}}}        
porter-operator-controller-manager-6fcd6f8d7c-tv74m:manager 2023-03-01T20:34:07Z    ERROR    Reconciler error    {"controller": "agentaction", "controllerGroup": "getporter.org", "controllerKind": "AgentAction", "AgentAction": {"name":"porter-t
est-me-v0-6-1-jzdz7-2mtb4","namespace":"vulcan"}, "namespace": "vulcan", "name": "porter-test-me-v0-6-1-jzdz7-2mtb4", "reconcileID": "34f839ab-be64-475c-ad3e-e12c2b44a56a", "error": "resolved agent configuration is not ready to be used. Waiting
 for the next retry", "errorVerbose": "resolved agent configuration is not ready to be used. Waiting for the next retry\nget.porter.sh/operator/controllers.(*AgentActionReconciler).resolveAgentConfig\n\t/workspace/controllers/agentaction_contro
ller.go:524\nget.porter.sh/operator/controllers.(*AgentActionReconciler).runPorter\n\t/workspace/controllers/agentaction_controller.go:184\nget.porter.sh/operator/controllers.(*AgentActionReconciler).Reconcile\n\t/workspace/controllers/agentact
ion_controller.go:94\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/co
ntroller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sig
s.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/cont
roller.go:235\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594"}                                                                                                                                                                       
porter-operator-controller-manager-6fcd6f8d7c-tv74m:manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler                                                                                                   
porter-operator-controller-manager-6fcd6f8d7c-tv74m:manager     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:329                                                                                        
porter-operator-controller-manager-6fcd6f8d7c-tv74m:manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem                                                                                                
porter-operator-controller-manager-6fcd6f8d7c-tv74m:manager     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:274                                                                                        
porter-operator-controller-manager-6fcd6f8d7c-tv74m:manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2                                                                                                      
porter-operator-controller-manager-6fcd6f8d7c-tv74m:manager     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:235 
```

## Version
v0.8.0

### PR DESCRIPTION
**Pull request by sgettys**
# What does this change
Previously when a volume existed that already satisfied the agent config plugins hash we would only return the temp volume claim. In this scenario however the temp volume claim can have already been deleted so we would return "nil" when we found a ready volume claim only. 

Now the ready volume claim is returned if its found, otherwise the temp claim is returned if its found, or finally a new empty one is created.

# What issue does it fix
Closes #169 

[1]: https://getporter.org/src/CONTRIBUTING.md#when-to-open-a-pull-request

# Notes for the reviewer
_Put any questions or notes for the reviewer here._
renamePluginVolume handles reconciling if the volume claim is the ready or temp claim. This scenario is just for resolving at action create time if a final claim (ready) exists, a temp claim exists, or if a new claim needs to be created.

# Checklist
- [x] Did you write tests?
- [ ] Did you write documentation?
- [ ] Did you make any API changes? Update the corresponding API documentation.

[contributors]: https://getporter.org/src/CONTRIBUTORS.md

### CODE REVIEW

File: controllers/agentconfig_controller.go [hunk 1]
```diff
@@ -191,8 +191,12 @@ func (r *AgentConfigReconciler) createEmptyPluginVolume(ctx context.Context, log
 	if err != nil {
 		return nil, false, err
 	}
-
-	if pluginPVC != nil || tempPVC != nil {
+	// If there is an exising claim then return it. This can be either the pluginPVC or a tempPVC depending on where in the process
```
Comment (schristoff) [inline controllers/agentconfig_controller.go:194]: Will we ever hit this step with a PVC that is stuck in setup/failed setup?

**Review by schristoff — APPROVED** [review]
One comment that I need clarification on but otherwise lgtm

File: controllers/agentconfig_controller.go (hunk 1 above)
Comment (sgettys) [reply controllers/agentconfig_controller.go:194]: We shouldn't hit this because the creation is handled separately and this is just checking for if a PVC exists. We're not actually managing the contents of the PV. If it failed in creation then it wouldn't be able to get here.
